name: Create Feature Branch
permissions: write-all

on:
  workflow_dispatch:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Grant execute permissions for the script
      run: chmod +x ./CreateFolder.sh

    - name: Run script to create folder and branch
      id: Folder_name
      run: |
        ./CreateFolder.sh
        
    - name: Use folder name variable
      run: echo "The result is ${{ steps.Folder_name.outputs.FOLDER_NAME }}"
    - name: Configurar sparse-checkout para archivos específicos
      run: |
        # Inicializa sparse-checkout
        git sparse-checkout init --cone

        # Selecciona solo los archivos que necesitas
        git sparse-checkout set ./prueba.txt ./carpeta/carpeta2/prueba4.txt

        # Cambia a la rama principal (main) para asegurarte de estar en una base limpia
        git checkout main

    - name: Create feature branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Generar un nombre aleatorio para la rama
        branch_name="feature/${{ steps.Folder_name.outputs.FOLDER_NAME }}"
        
        # Crear la nueva rama y hacer push al repositorio remoto
        git checkout -b "$branch_name"
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        ls
        git status
        
          
        # Agrega los archivos que deseas incluir en la nueva rama
        git add .
          
          # Realiza el commit de los cambios
        git commit -m "Agregados archivos específicos a la nueva rama"
        git push origin "$branch_name"  
      
