name: Tag Successor on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - laboratorio

jobs:
  tag_successor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get the latest tag from source branch
      id: get_tag
      run: |
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Create successor tag
      id: create_tag
      run: |
        IFS='.' read -r -a tag_parts <<< "${{ env.latest_tag }}"
        new_tag="${tag_parts[0]}.${tag_parts[1]}.$((tag_parts[2] + 1))"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Checkout destination branch
      uses: actions/checkout@v2
      with:
        ref: integracion

    - name: Push successor tag to destination branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag ${{ env.new_tag }}
        git push origin ${{ env.new_tag }}
